services:
  config-service:
    build:
      context: ./config-service
    container_name: config-service
    ports:
      - 8888:8888
    networks:
      - spring-cloud-network
  discovery-service:
    build:
      context: ./discovery-service
    container_name: discovery-service
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network
    depends_on:
      config-service:
        condition: service_started
  api-gateway-service:
    build:
      context: ./api-gateway-service
    container_name: api-gateway-service
    ports:
      - 8762:8762
    networks:
      - spring-cloud-network
    depends_on:
      config-service:
        condition: service_started
networks:
  spring-cloud-network:
    driver: bridge