INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(37, 'Drame', 18);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(38, 'Guerre', 10752);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(39, 'Action', 28);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(40, 'Thriller', 53);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(41, 'Science-Fiction', 878);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(42, 'Mystère', 9648);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(43, 'Aventure', 12);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(44, 'Fantastique', 14);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(45, 'Romance', 10749);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(46, 'Comédie', 35);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(47, 'Crime', 80);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(48, 'Documentaire', 99);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(49, 'Animation', 16);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(50, 'Familial', 10751);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(51, 'Histoire', 36);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(52, 'Horreur', 27);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(53, 'Western', 37);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(54, 'Musique', 10402);
INSERT INTO "dvdtheque-service".genre
(id, "name", tmdb_id)
VALUES(55, 'Téléfilm', 10770);